# Generated by Django 4.1.2 on 2022-12-03 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='メッセージを記入', max_length=150, verbose_name='お知らせ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to=settings.AUTH_USER_MODEL, verbose_name='教師')),
            ],
        ),
    ]
